[project]
name = "ABVME"
version = "0.1.8"
description = "Asset Bundles Viewer Modifier and Exporter."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyside6==6.7.2",
    "unitypy==1.23.0",
]

[dependency-groups]