[project]
name = "ABVME"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyside6==6.7.2",
    "unitypy==1.23.0",
]

[dependency-groups]